version: '3'
services:
  api:
    build: .
    ports:
     - "9000:9000"
     - "9222:9222"
     - "3000:3000"
     - "1883:1883"
    volumes:
    # host: docker
     - ./:/top/app
    links: 
     - "db:database"
    # env_file:
    # - variables.env
  db:
    image: "mongo:latest"
    ports: 
     - "27017:27017"